### ISSUE TITLE
UI.Window show(): crash after compilation with SDK 3.1 and latest pebble.js

### ISSUE THREAD

**Issue by rabenhorst** [pebble/pebblejs#79] opened 2015-07-19 19:02 UTC
I just compiled my Watchapp with the latest SDK 3.1 and latest pebble JS. Before it worked without problems but now it crash every third or fourth time execution this code:

``` javascript
var setSceneSuccessWindows = new UI.Window({fullscreen: true});
var image = new UI.Image({
  position: new Vector2(0, 0),
  size: new Vector2(144, 168),
  image: successImage,
  backgroundColor: 'black'
});
setSceneSuccessWindows.add(image);
setTimeout(function () {
  setSceneSuccessWindows.hide();
}, 1000);
setSceneSuccessWindows.show();
}
```

Crash log:

```
[INFO    ] E ault_handling.c:77 App fault! {000d9985-39b4-42b2-8d92-e2fa6e329a07} PC: 0x1b22 LR: 0x1aed
[WARNING ]    Program Counter (PC):     0x1b22 /Users/mactron/dev/pebble-dev/projects/simbble_hue/src/util/list1.h:42
[WARNING ]      Link Register (LR):     0x1aed /Users/mactron/dev/pebble-dev/projects/simbble_hue/build/../src/simply/simply_res.c:80
[INFO    ] JS: stopping app: 000D9985-39B4-42B2-8D92-E2FA6E329A07 simbble hue
```

**Comment by Meiguro** [comment] 2015-07-22 00:49
Thanks for reporting the issue, and the logs! Hmm, simply_res.c:80 is not a call to a list1 function. It seems you are on an older commit, such as 020e55b3ae78857686fbe648a199921d72e7e2a4.

Can you try again with master fa651024703fd8a2000766cdb2ade0232d02e352 merged into your branch?

**Comment by mactr0n** [comment] 2015-08-01 12:42
I'm on fce2f79.

**Comment by Meiguro** [comment] 2015-08-03 10:32
Ah, sorry, I should have clarified that I tried your example but it didn't result in a crash for me, so I started investigated beyond that. I definitely want to fix this, but I'll need a way to reproduce this. There are one of four things you can do:

1. Check the md5sum of your `simply_res.c`. `md5sum src/simply/simply_res.c` results in `993edab77811d0abde70410f8a71c11c  src/simply/simply_res.c` for me. If it's different, there may have been a bad merge down the line. If it's the same, try the other options.

2. Is your project private? At the very least, you can email me your build directory (it'll have debug symbols); plus I'll need the source files `simply_res.c` and `list1.h`. Although, more helpful is the entire directory. The git history is a plus, but I understand if you want to leave that out. My email is in the commit history.

3. If that's not an option, I would try making a minimal example that crashes. Try to see if your minimal example you have here crashes (without all of your other logic). If it does, maybe something is missing that causes it not to crash on my end. Try with a public image you're willing to share.

4. If you're unable to make a minimal example that crashes it, I would try cloning the pebble.js repo and copying (not cherry-picking) your JavaScript app over. If there are modifications to the base pebble.js however, 2 or 3 are better options.

**Comment by Meiguro** [comment] 2015-08-17 18:23
Hey @mactr0n, I eventually found crash issues with windows on basalt that may be what you have been running into! Could you give it another try? If it still crashes, let me know what firmware version you encounter the crash on. I'll load it on a Pebble Time and try it again. For memory issues, that may be the one thing I'm not replicating correctly.

**Comment by youtux** [comment] 2015-08-18 11:36
Hi @Meiguro, I'm experiencing the same bug. You can replicate it with this `app.js`:
```javascript
var UI = require('ui');

badCard = new UI.Card({
  title: 'bad card',
  body: 'some long long long long long long long long long text'
});
var menu = new UI.Menu({sections:[]});

badCard.show();
menu.show();
badCard.show();
```
getting the following log:
```
Installing app...
App install succeeded.
[13:31:34] ault_handling.c:78> App fault! {133215f0-cf20-4c05-997b-3c9be5a64e5b} PC: 0x676e6f6c LR: 0x805de3f
Program Counter (PC)    : 0x676e6f6c ???
Link Register (LR)      : 0x805de3f  ???
```

Note that if you replace `some long long long long long long long long long text` with `some short text` the app will still crash, but on the terminal you won't see the `App fault` message.
I found out that it started on commit 3367afcdcfeeeacd06b8ca3868db445344dac232 (git bisect <3). I'm using Mac OS X 10.11 Public Beta (15A243d), Pebble SDK 3.2.1.

**Comment by Meiguro** [comment] 2015-08-18 12:08
Thanks @youtux, I've reverted that particular commit. That seemed to just create more of an edge case. Does that solve the issue?

**Comment by youtux** [comment] 2015-08-18 12:13
That fixed the crash, but it intruduces a new bug: take this app:
```javascript
var UI = require('ui');

badCard = new UI.Card({
  title: 'bad card',
  body: 'some long long long long long long long long long text'
});
var menu = new UI.Menu({sections:[]});

// badCard.show();
menu.show();
badCard.show();
```
It correctly push the `menu` and the `badCard`, but when you click back twice, you don't quit the application, but you are stuck on the `badCard`, which strangely is also in fullscreen, and you have to longClick back to quit.

**Comment by Meiguro** [comment] 2015-08-18 13:13
Ah, that was a hasty modification. I've disabled animations on basalt for the time being since I want master to at least work reasonably. There are no animations, and windows are now only destroyed on deinit which I was hoping to avoid.

**Comment by youtux** [comment] 2015-08-18 16:04
👍

**Closed** 2020-05-19 06:41 UTC
